cloud:
  aws:
    bucketName: adityas3bucket
    account: 
      secretKey: Enter AWS account secret key here
      region: us-east-1
      accessKey: Enter AWS account access key here
spring:
  application:
    name: springboot-aws
server:
  port: 9191