cloud:
  aws:
    bucketName: adityas3bucket
    account:
      secretKey: LyMNNC003E92TGCP4Tp4UCoKegywwww3XHv0QW7fd9HC
      region: us-east-1
      accessKey: AKIAUGXLJ66NDwwwwwZKHWMBOS
spring:
  application:
    name: springboot-aws
server:
  port: 9191